---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homepage

background:
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

useEqualHeights: true

layout:
  Hypervisor:
    header: true
    style: row
    columns: 3
  DNS:
    header: true
    style: row
    columns: 2
  Network:
    header: true
    style: row
    columns: 3
  Storage:
    header: true
    style: row
    columns: 2
  Media:
    header: true
    style: row
    columns: 2
  Home Automation:
    header: true
    style: row
    columns: 3
  File Hosting:
    header: true
    style: row
    columns: 2
  Other:
    header: true
    style: row
    columns: 4
  Links:
    header: true
    style: row
    columns: 4
